"""Runtime evaluator for ``forms/<ID>/rubric.yaml`` checks.

Each form ships a ``rubric.yaml`` whose checks were authored as *prose* (plus
``depends_on_keys`` and a ``severity``). The prose is formulaic — it was
generated by one pipeline — so most checks compile to executable assertions:

- non-empty requirements (single key, key lists, ``a.{b,c}`` brace groups)
- date sanity (not in the future, on-or-before/after another date key)
- cross-field equality / must-differ checks
- "exactly one of" / "at most one of" enum selections (validated against the
  check's own value list or the form's ``schema.json`` enum)
- conditional requirements ("If X is true / = 'v' / is set, Y must ...")
- mutually-exclusive booleans
- statutory name-suffix requirements (quoted suffix lists)
- "not a P.O. Box" address checks
- format checks (email, single uppercase letter, contains a comma)
- fee totals (base + expedite premium) where the prose states one base amount
- at-least-one / exactly-one signer-block requirements
- paired name/address roster rows

A check whose prose does not compile is **never silently dropped**: it is
reported as a ``MANUAL_REVIEW`` issue carrying the original prose, so a human
(or agent) can still apply it.

Severity mapping: rubric ``required`` -> ``error``, ``optional`` ->
``warning``, ``advisory`` -> ``info``; non-compilable checks -> ``manual``.

Usage::

    from engine import rubric
    result = rubric.evaluate("LLC_MLLC-6", case)
    # {"ok": bool, "issues": [...], "stats": {...}}

    python -m engine.rubric <FORM_ID> <case.json> [forms_root]
    python -m engine.rubric --coverage [forms_root]   # compile-rate report
"""
import json
import re
import sys
from datetime import date, datetime
from pathlib import Path

from . import canonical
from .mapping import entries as mapping_entries

# --------------------------------------------------------------------------
# severities
_SEV_MAP = {"required": "error", "optional": "warning", "advisory": "info"}

# dotted canonical key (optionally with [N] indexes)
_KEY = r"[A-Za-z_][A-Za-z0-9_]*(?:\[\d+\])?(?:\.[A-Za-z0-9_]+(?:\[\d+\])?)+"
_KEY_RE = re.compile(_KEY)
# brace group: filing.contact.{name,phone,email} or {name, phone, email}
_BRACE_RE = re.compile(r"(" + _KEY[:-1] + r"?)\.\{([^}]+)\}")

_MAINE = {"maine", "me"}
_POBOX_RE = re.compile(r"(?i)\b(p\.?\s*o\.?\s*box|post\s+office\s+box)")
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

_EXPEDITE_PREMIUM = {
    None: 0, "": 0,
    "hold_for_pickup": 0,
    "24h_next_business_day": 50,
    "immediate_same_day": 100,
}

_DATE_FORMATS = (
    "%Y-%m-%d", "%m/%d/%Y", "%m/%d/%y", "%m-%d-%Y",
    "%B %d, %Y", "%b %d, %Y", "%d %B %Y", "%B %d %Y",
)


def _parse_date(value):
    """Parse a case date value to ``datetime.date`` or ``None``."""
    if isinstance(value, date):
        return value
    s = str(value or "").strip()
    if not s:
        return None
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(s, fmt).date()
        except ValueError:
            continue
    return None


def _is_empty(value):
    if value is None:
        return True
    if isinstance(value, str):
        return value.strip() == ""
    if isinstance(value, (list, tuple, set, dict)):
        return len(value) == 0
    return False


def _truthy(value):
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    if isinstance(value, (int, float)):
        return value != 0
    s = str(value).strip().lower()
    if s in ("no", "false", "0", "off", "n", "", "none", "unchecked"):
        return False
    return bool(s)


def _norm(value):
    return str(value or "").strip().lower()


def _money(value):
    """Parse a fee value ('$135.00', 135, '135') to float, or None."""
    if value is None:
        return None
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    s = re.sub(r"[$,\s]", "", str(value))
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


# --------------------------------------------------------------------------
# assertion primitives — each is fn(case, ctx) -> list of violation dicts
# ctx carries {"today": date}. Violations: {"code", "keys", "detail"}.

def _v(code, keys, detail):
    if isinstance(keys, str):
        keys = [keys]
    return {"code": code, "keys": list(keys), "detail": detail}


def a_nonempty(keys):
    def check(case, ctx):
        out = []
        for k in keys:
            if _is_empty(canonical.get(case, k)):
                out.append(_v("MISSING_REQUIRED", k, f"{k} is empty"))
        return out
    return check


def a_at_least_one(keys):
    def check(case, ctx):
        if any(not _is_empty(canonical.get(case, k)) for k in keys):
            return []
        return [_v("AT_LEAST_ONE_REQUIRED", keys,
                   "none of the alternatives is populated: "
                   + ", ".join(keys))]
    return check


def a_group_choice(groups, exactly_one):
    """At-least-one (or exactly-one) of several all-populated key groups."""
    def check(case, ctx):
        filled = [g for g in groups
                  if all(not _is_empty(canonical.get(case, k)) for k in g)]
        partial = [g for g in groups
                   if any(not _is_empty(canonical.get(case, k)) for k in g)]
        allkeys = [k for g in groups for k in g]
        if not filled:
            return [_v("SIGNER_BLOCK_REQUIRED", allkeys,
                       "no complete block is populated among: "
                       + " | ".join("+".join(g) for g in groups))]
        if exactly_one and len(partial) > 1:
            return [_v("MULTIPLE_BLOCKS_POPULATED", allkeys,
                       "more than one mutually-exclusive block is populated")]
        return []
    return check


def a_not_future(key, ref_key=None):
    def check(case, ctx):
        val = canonical.get(case, key)
        if _is_empty(val):
            return []
        d = _parse_date(val)
        if d is None:
            return [_v("UNPARSEABLE_DATE", key,
                       f"{key} = {val!r} is not a recognizable date")]
        if ref_key:
            rv = canonical.get(case, ref_key)
            if _is_empty(rv):
                return []
            rd = _parse_date(rv)
            if rd is None:
                return []
            if d > rd:
                return [_v("DATE_IN_FUTURE", [key, ref_key],
                           f"{key} ({d}) is after {ref_key} ({rd})")]
            return []
        if d > ctx["today"]:
            return [_v("DATE_IN_FUTURE", key,
                       f"{key} ({d}) is in the future")]
        return []
    return check


def a_date_order(key_a, op, key_b):
    """op: '<=', '>=', '<' — assert date(key_a) op date(key_b)."""
    def check(case, ctx):
        va, vb = canonical.get(case, key_a), canonical.get(case, key_b)
        if _is_empty(va) or _is_empty(vb):
            return []
        da, db = _parse_date(va), _parse_date(vb)
        out = []
        if da is None:
            out.append(_v("UNPARSEABLE_DATE", key_a,
                          f"{key_a} = {va!r} is not a recognizable date"))
        if db is None:
            out.append(_v("UNPARSEABLE_DATE", key_b,
                          f"{key_b} = {vb!r} is not a recognizable date"))
        if out or da is None or db is None:
            return out
        ok = {"<=": da <= db, ">=": da >= db, "<": da < db}[op]
        if not ok:
            word = {"<=": "on or before", ">=": "on or after",
                    "<": "strictly before"}[op]
            return [_v("DATE_ORDER", [key_a, key_b],
                       f"{key_a} ({da}) must be {word} {key_b} ({db})")]
        return []
    return check


def a_equals(key_a, key_b, alt_key=None):
    def check(case, ctx):
        va, vb = canonical.get(case, key_a), canonical.get(case, key_b)
        if _is_empty(va) or _is_empty(vb):
            return []
        if _norm(va) == _norm(vb):
            return []
        if alt_key is not None:
            valt = canonical.get(case, alt_key)
            if not _is_empty(valt) and _norm(va) == _norm(valt):
                return []
        return [_v("VALUE_MISMATCH", [key_a, key_b],
                   f"{key_a} ({va!r}) does not match {key_b} ({vb!r})")]
    return check


def a_differs(key_a, key_bs):
    def check(case, ctx):
        va = canonical.get(case, key_a)
        if _is_empty(va):
            return []
        out = []
        for kb in key_bs:
            vb = canonical.get(case, kb)
            if _is_empty(vb):
                continue
            if _norm(va) == _norm(vb):
                out.append(_v("VALUES_MUST_DIFFER", [key_a, kb],
                              f"{key_a} must differ from {kb} "
                              f"(both are {va!r})"))
        return out
    return check


def a_not_in(key, forbidden, require_nonempty=False):
    def check(case, ctx):
        val = canonical.get(case, key)
        if _is_empty(val):
            if require_nonempty:
                return [_v("MISSING_REQUIRED", key, f"{key} is empty")]
            return []
        if _norm(val) in forbidden:
            return [_v("FORBIDDEN_VALUE", key,
                       f"{key} must not be {val!r}")]
        return []
    return check


def a_one_of(key, allowed, required):
    def check(case, ctx):
        val = canonical.get(case, key)
        if _is_empty(val):
            if required:
                opts = (" to one of: " + ", ".join(sorted(allowed))
                        if allowed else " (exactly one option)")
                return [_v("CHOICE_REQUIRED", key,
                           f"{key} must be set" + opts)]
            return []
        if allowed and _norm(val) not in {a.lower() for a in allowed}:
            return [_v("ENUM_INVALID", key,
                       f"{key} = {val!r} is not one of: "
                       + ", ".join(sorted(allowed)))]
        return []
    return check


def a_mutex_bool(key_a, key_b):
    def check(case, ctx):
        if _truthy(canonical.get(case, key_a)) and \
                _truthy(canonical.get(case, key_b)):
            return [_v("MUTUALLY_EXCLUSIVE", [key_a, key_b],
                       f"{key_a} and {key_b} cannot both be true")]
        return []
    return check


def a_not_pobox(key, require_nonempty=False):
    def check(case, ctx):
        val = canonical.get(case, key)
        if _is_empty(val):
            if require_nonempty:
                return [_v("MISSING_REQUIRED", key, f"{key} is empty")]
            return []
        if _POBOX_RE.search(str(val)):
            return [_v("PO_BOX_FORBIDDEN", key,
                       f"{key} must not be a P.O. Box (got {val!r})")]
        return []
    return check


def a_contains_one_of(key, substrings, extra=None, skip_values=(),
                      anchored=False):
    """``key`` (when set) must contain one of ``substrings`` (case-insens.).

    ``extra``: (gate_key, more_substrings) — the extra suffixes also satisfy
    the check, but only when the gate key is truthy.

    ``anchored``: when True, the match is anchored to the END of the value
    (after stripping trailing whitespace/punctuation) rather than a
    match-anywhere substring test. This is the correct semantics for
    statutory entity-name *suffix* requirements: a plain substring test
    false-positives on names that merely embed a 2-char token — e.g. "LC"
    inside "Malcolm Holdings" or "Falcon Realty" would otherwise satisfy an
    LLC-suffix check. End-anchoring rejects those while still accepting
    "Acme LLC", "Acme L.L.C.", and "Acme, Inc.".
    """
    def _matches(low, sub):
        sub = sub.lower()
        if not anchored:
            return sub in low
        # Anchor to the end of the name. Strip trailing whitespace and
        # punctuation from the *name* so "Acme LLC." matches suffix "LLC",
        # while the suffix keeps its own trailing '.' (e.g. "Inc.") so both
        # "Acme, Inc." and "Acme Inc" are accepted.
        tail = low.rstrip(" \t.,;")
        sub_bare = sub.rstrip(" \t.,;")
        return tail.endswith(sub) or tail.endswith(sub_bare)

    def check(case, ctx):
        val = canonical.get(case, key)
        if _is_empty(val):
            return []
        low = _norm(val)
        if low in {s.lower() for s in skip_values}:
            return []
        allowed = list(substrings)
        if extra is not None:
            gate_key, more = extra
            if _truthy(canonical.get(case, gate_key)):
                allowed = allowed + list(more)
        if any(_matches(low, s) for s in allowed):
            return []
        return [_v("NAME_AFFIX_REQUIRED", key,
                   f"{key} = {val!r} must "
                   + ("end with" if anchored else "contain")
                   + " one of: "
                   + ", ".join(substrings)
                   + (f" (or, when {extra[0]} is true: "
                      + ", ".join(extra[1]) + ")" if extra else ""))]
    return check


def a_format(key, kind):
    """kind: 'email' | 'single_uppercase_letter' | 'contains_comma'."""
    def check(case, ctx):
        val = canonical.get(case, key)
        if _is_empty(val):
            return []
        s = str(val).strip()
        ok = {"email": bool(_EMAIL_RE.match(s)),
              "single_uppercase_letter": bool(re.fullmatch(r"[A-Z]", s)),
              "contains_comma": "," in s,
              "positive_integer": bool(re.fullmatch(r"[1-9]\d*", s))}[kind]
        if not ok:
            return [_v("FORMAT_INVALID", key,
                       f"{key} = {val!r} fails format check ({kind})")]
        return []
    return check


def a_fee(total_key, expedite_key, base, minimum=False):
    def check(case, ctx):
        total = _money(canonical.get(case, total_key))
        if total is None:
            return []  # fee total not asserted in the case — nothing to check
        tier = canonical.get(case, expedite_key) if expedite_key else None
        tier_s = _norm(tier) if tier is not None else ""
        if tier_s not in {_norm(k) for k in _EXPEDITE_PREMIUM if k}.union({""}):
            return [_v("UNKNOWN_EXPEDITE_TIER", expedite_key or total_key,
                       f"{expedite_key} = {tier!r} is not a known tier")]
        premium = _EXPEDITE_PREMIUM.get(tier_s or None, 0)
        expected = base + premium
        if minimum:
            if total < expected:
                return [_v("FEE_MISMATCH", total_key,
                           f"{total_key} (${total:g}) is below the "
                           f"${expected:g} minimum (${base:g} base"
                           + (f" + ${premium:g} expedite" if premium else "")
                           + ")")]
            return []
        if abs(total - expected) > 0.005:
            return [_v("FEE_MISMATCH", total_key,
                       f"{total_key} (${total:g}) != expected "
                       f"${expected:g} (${base:g} base"
                       + (f" + ${premium:g} expedite" if premium else "")
                       + ")")]
        return []
    return check


def a_conditional(predicate, then_assertions, pred_text):
    def check(case, ctx):
        if not predicate(case):
            return []
        out = []
        for sub in then_assertions:
            for viol in sub(case, ctx):
                viol = dict(viol)
                viol["code"] = ("CONDITIONAL_FORBIDDEN"
                                if viol["code"] == "MUST_BE_ABSENT"
                                else "CONDITIONAL_MISSING"
                                if viol["code"] in ("MISSING_REQUIRED",
                                                    "CHOICE_REQUIRED")
                                else viol["code"])
                viol["detail"] = f"when {pred_text}: " + viol["detail"]
                out.append(viol)
        return out
    return check


def a_absent(keys):
    def check(case, ctx):
        out = []
        for k in keys:
            if not _is_empty(canonical.get(case, k)):
                out.append(_v("MUST_BE_ABSENT", k,
                              f"{k} must be empty"))
        return out
    return check


def a_truthy(keys):
    def check(case, ctx):
        out = []
        for k in keys:
            if not _truthy(canonical.get(case, k)):
                out.append(_v("MISSING_REQUIRED", k,
                              f"{k} must be true"))
        return out
    return check


def a_both_or_neither(key_a, key_b):
    def check(case, ctx):
        ea, eb = (_is_empty(canonical.get(case, key_a)),
                  _is_empty(canonical.get(case, key_b)))
        if ea != eb:
            return [_v("PAIRED_FIELDS_INCOMPLETE", [key_a, key_b],
                       f"{key_a} and {key_b} must be populated together "
                       "(or both left empty)")]
        return []
    return check


def a_name_address_pairs(pairs):
    def check(case, ctx):
        out = []
        for name_key, addr_key in pairs:
            if not _is_empty(canonical.get(case, name_key)) and \
                    _is_empty(canonical.get(case, addr_key)):
                out.append(_v("PAIRED_FIELDS_INCOMPLETE",
                              [name_key, addr_key],
                              f"{name_key} is populated but {addr_key} "
                              "is empty"))
        return out
    return check


# --------------------------------------------------------------------------
# prose -> assertion compiler

def _expand_braces(text):
    """Expand ``a.b.{x,y,z}`` (and ``a.{x, y}``) into ``a.b.x, a.b.y, ...``."""
    def repl(m):
        prefix = m.group(1)
        parts = [p.strip() for p in m.group(2).split(",")]
        return ", ".join(f"{prefix}.{p}" for p in parts if p)
    return _BRACE_RE.sub(repl, text)


def _quoted(text):
    """All single-quoted strings in ``text`` (smart quotes tolerated)."""
    return re.findall(r"[‘']([^'’]+)[’']", text)


def _enum_tokens(text):
    """Quoted strings that look like enum tokens (snake_case identifiers).

    Filters prose quotes like 'X one box only' out of option lists.
    """
    return {t for t in _quoted(text) if re.fullmatch(r"[a-z0-9_]+", t)}


def _strip_parens(text):
    """Drop parentheticals that carry no dotted keys or dollar amounts.

    Quoted-suffix and enum parentheticals are consumed from the *raw*
    description by their dedicated handlers before this runs, so plain
    commentary parens (statute cites, 'Shape D', 'must match SOS record')
    can be dropped safely. Runs to fixpoint to unwrap nesting.
    """
    def repl(m):
        inner = m.group(1)
        if _KEY_RE.search(inner) or "$" in inner \
                or "vice versa" in inner or "if low-profit" in inner:
            return m.group(0)
        return ""
    prev = None
    out = text
    while out != prev:
        prev = out
        out = re.sub(r"\(([^()]*)\)", repl, out)
    out = re.sub(r"\s+", " ", out)
    # tighten dangling space before sentence punctuation, but never glue a
    # relative ".key" fragment onto the previous word ("street and .city")
    out = re.sub(r"\s+([.,;])(?=\s|$)", r"\1", out)
    return out.strip()


def _parse_condition(text, carried_key=None):
    """Parse a condition clause -> (predicate, key, text) or None."""
    text = text.strip()
    if re.search(r"\b\w+_N\b", text):
        return None  # ungrounded row template ("partner_entity_N.name")
    m = re.match(rf"^({_KEY})\s+is\s+true$", text)
    if m:
        k = m.group(1)
        return (lambda c, k=k: _truthy(canonical.get(c, k))), k, f"{k} is true"
    m = re.match(rf"^({_KEY})\s+is\s+false$", text)
    if m:
        k = m.group(1)
        return ((lambda c, k=k: not _truthy(canonical.get(c, k))), k,
                f"{k} is false")
    m = re.match(rf"^({_KEY})\s*=\s*'([^']+)'$", text)
    if m:
        k, v = m.group(1), m.group(2)
        return ((lambda c, k=k, v=v: _norm(canonical.get(c, k)) == v.lower()),
                k, f"{k} = '{v}'")
    # elliptical: "if 'noncommercial'" / "If false" — reuse the carried key
    m = re.match(r"^'([^']+)'$", text)
    if m and carried_key:
        k, v = carried_key, m.group(1)
        return ((lambda c, k=k, v=v: _norm(canonical.get(c, k)) == v.lower()),
                k, f"{k} = '{v}'")
    if text == "false" and carried_key:
        k = carried_key
        return ((lambda c, k=k: not _truthy(canonical.get(c, k))), k,
                f"{k} is false")
    if text == "true" and carried_key:
        k = carried_key
        return ((lambda c, k=k: _truthy(canonical.get(c, k))), k,
                f"{k} is true")
    m = re.match(rf"^({_KEY})\s+is\s+(?:set|populated|non-empty)$", text)
    if m:
        k = m.group(1)
        return ((lambda c, k=k: not _is_empty(canonical.get(c, k))), k,
                f"{k} is set")
    m = re.match(rf"^({_KEY})\s+is\s+not\s+'([^']+)'(?:\s*/\s*'([^']+)')?$",
                 text)
    if m:
        k = m.group(1)
        vals = {m.group(2).lower()}
        if m.group(3):
            vals.add(m.group(3).lower())
        def pred(c, k=k, vals=vals):
            v = canonical.get(c, k)
            return not _is_empty(v) and _norm(v) not in vals
        return pred, k, f"{k} is not " + "/".join(sorted(vals))
    m = re.match(rf"^({_KEY})\s+differs\s+from\s+({_KEY})$", text)
    if m:
        ka, kb = m.group(1), m.group(2)
        def pred(c, ka=ka, kb=kb):
            va, vb = canonical.get(c, ka), canonical.get(c, kb)
            return (not _is_empty(va) and not _is_empty(vb)
                    and _norm(va) != _norm(vb))
        return pred, ka, f"{ka} differs from {kb}"
    return None


def _name_address_pairs_from_keys(keys):
    names = [k for k in keys if k.endswith(".name")]
    pairs = [(n, n[: -len(".name")] + ".address") for n in names
             if n[: -len(".name")] + ".address" in keys]
    return pairs


def _parse_consequence(text, cond_key=None, carried_subject=None,
                       check_keys=()):
    """Parse a conditional consequence -> (assertions, subject) or None."""
    text = text.strip().rstrip(".;").strip()

    # special: roster-pair consequence ("all populated X rows must have both
    # name and address") — pairs are recovered from depends_on_keys
    if re.search(r"all populated \S+ rows must have both name and address",
                 text, re.I):
        pairs = _name_address_pairs_from_keys(check_keys)
        if pairs:
            return [a_name_address_pairs(pairs)], None
        return None
    if re.search(r"\b\w+_N\b", text):
        return None  # ungrounded row template — needs human review
    if re.search(r"\bexactly one\b.*\boptions? (?:is|must be) selected",
                 text, re.I):
        keys_in = [k for k in _KEY_RE.findall(text) if "_N" not in k]
        target = keys_in[0] if keys_in else None
        if target:
            return [a_one_of(target, set(), required=True)], target
        return None

    # split off the subject(s)
    text = re.sub(r"^at least\s+", "", text)
    m = re.match(rf"^({_KEY})(?: [Aa][Nn][Dd] ({_KEY}))?\s+(.*)$", text)
    if m:
        subjects = [m.group(1)] + ([m.group(2)] if m.group(2) else [])
        pred = m.group(3)
    elif re.match(r"^it\s+", text):
        subject = carried_subject or cond_key
        if subject is None:
            return None
        subjects = [subject]
        pred = text[3:].strip()
    else:
        return None

    subject = subjects[0]
    if re.search(rf"\(or {_KEY} when (?:set|populated)\)", pred):
        return None  # alternate-subject fallback — keep for human review
    vice_versa = "vice versa" in pred
    pred = re.sub(r"\(?and vice versa\)?", "", pred).strip()

    if re.match(r"^(?:must (?:also |both |all )?(?:be )?|(?:is|are) "
                r"(?:both )?)(?:non-empty|set|populated)$", pred):
        if vice_versa and cond_key and len(subjects) == 1:
            return [a_both_or_neither(cond_key, subject)], subject
        return [a_nonempty(subjects)], subject
    if re.match(r"^must (?:also )?be true$", pred):
        return [a_truthy(subjects)], subject
    if re.match(r"^(?:must|should) (?:also )?be (?:absent|empty|left empty)$",
                pred):
        return [a_absent(subjects)], subject
    if re.match(r"^must not be a P\.?O\.? Box$", pred, re.I):
        return [a_not_pobox(subject)], subject
    if "must look like a valid email" in pred:
        return [a_format(subject, "email")], subject
    if "single uppercase letter" in pred:
        return [a_format(subject, "single_uppercase_letter")], subject
    m = re.match(rf"^(?:must be|is|should be) on or after ({_KEY})$", pred)
    if m:
        return [a_date_order(subject, ">=", m.group(1))], subject
    m = re.match(rf"^(?:must be|is|should be) on or before ({_KEY})$", pred)
    if m:
        return [a_date_order(subject, "<=", m.group(1))], subject
    if "must contain one of" in pred:
        quoted = _quoted(pred)
        if quoted:
            # entity-name suffix requirement: anchor to end of name so a
            # 2-char token ('LP', 'LC') doesn't match mid-name.
            return [a_contains_one_of(subject, quoted, anchored=True)], subject
    m = re.match(rf"^must not equal '([^']+)'(?: or '([^']+)')?$", pred)
    if m:
        vals = {m.group(1).lower()}
        if m.group(2):
            vals.add(m.group(2).lower())
        return [a_not_in(subject, vals)], subject
    return None


def _compile_conditional(desc, schema_enums, check_keys=()):
    """Compile one-or-more "If <cond>, <consequence>" sentences, or None."""
    sentences = re.split(r"(?<=[.;])\s+(?=[Ii]f\b)", desc)
    # also split a single sentence on '; if'
    parts = []
    for s in sentences:
        parts.extend(re.split(r";\s*(?=if\b)", s, flags=re.I))
    assertions = []
    carried_key = None
    carried_subject = None
    matched_any = False
    noop = re.compile(r"not required|is also valid|no meeting was held|"
                      r"need not", re.I)
    for part in parts:
        part = part.strip()
        if not part:
            continue
        m = re.match(r"^[Ii]f\s+(.+?),\s*(.+)$", part)
        if not m:
            # trailing non-conditional sentence: tolerate pure no-ops
            # ("...is not required." / "Zero is also valid...")
            if matched_any and noop.search(part):
                continue
            return None
        cond = _parse_condition(m.group(1).strip(), carried_key)
        if cond is None:
            if matched_any and noop.search(part):
                continue
            return None
        predicate, cond_key, pred_text = cond
        cons = _parse_consequence(m.group(2), cond_key, carried_subject,
                                  check_keys)
        if cons is None:
            if matched_any and noop.search(part):
                continue
            return None
        carried_key = cond_key
        sub_assertions, subject = cons
        if subject:
            carried_subject = subject
        assertions.append(a_conditional(predicate, sub_assertions, pred_text))
        matched_any = True
    return assertions or None


def _enum_for(key, schema_enums):
    return schema_enums.get(key, set())


def compile_check(check, schema_enums=None):
    """Compile one rubric check to a list of assertions, or ``None``.

    ``schema_enums`` maps dotted canonical keys to their schema enum values
    (used to validate "exactly one of ... options is selected" checks).
    """
    schema_enums = schema_enums or {}
    raw = (check.get("description") or "").strip()
    keys = list(check.get("depends_on_keys") or [])
    if not raw:
        return None
    desc = _expand_braces(re.sub(r"\s+", " ", raw))

    # ---- fee checks (before parenthetical stripping; need the $ text) ----
    if "total_fees_dollars" in desc:
        total_key = next((k for k in keys if "total_fees" in k),
                         "filing.total_fees_dollars")
        exp_key = next((k for k in keys if "expedited" in k),
                       "filing.expedited_service")
        # base fee depending on home jurisdiction is still machine-checkable
        m = re.search(rf"equals the base fee \(\$(\d+) if ({_KEY}) is "
                      rf"Maine/ME, else \$(\d+)\)", desc)
        if m:
            dom, jkey, foreign = (float(m.group(1)), m.group(2),
                                  float(m.group(3)))

            def fee_by_jurisdiction(case, ctx, total_key=total_key,
                                    exp_key=exp_key, jkey=jkey, dom=dom,
                                    foreign=foreign):
                j = _norm(canonical.get(case, jkey))
                if not j:
                    return []
                base = dom if j in _MAINE else foreign
                return a_fee(total_key, exp_key, base)(case, ctx)
            return [fee_by_jurisdiction]
        if re.search(r"bundled|accompanying-form|entity.type|entity type|"
                     r"month|\bor \$", desc, re.I):
            return None  # genuinely needs facts not in the case
        if re.search(r"No Filing Fee", desc):
            return [a_fee(total_key, exp_key, 0.0)]
        m = re.search(r">=\s*\$(\d+(?:\.\d+)?)", desc)
        if m:
            return [a_fee(total_key, exp_key, float(m.group(1)),
                          minimum=True)]
        m = re.search(r"is approximately \$(\d+(?:\.\d+)?)", desc)
        if m:
            return [a_fee(total_key, exp_key, float(m.group(1)),
                          minimum=True)]
        amounts = {float(a) for a in re.findall(r"\$(\d+(?:\.\d+)?)", desc)
                   if float(a) not in (50.0, 100.0, 0.0)}
        m = re.search(r"equals (?:the )?\$(\d+(?:\.\d+)?)", desc)
        if m and len(amounts) <= 1:
            return [a_fee(total_key, exp_key, float(m.group(1)))]
        return None

    # ---- LLC-style suffix list with a low-profit extension ----
    if re.search(r"ends with one of|must contain one of|contains a statutory",
                 desc) and "If " not in desc[:3]:
        if "abbreviation" in desc:
            return None  # open-ended suffix list — cannot enumerate
        m = re.match(rf"^({_KEY})", desc)
        if m and _quoted(desc):
            key = m.group(1)
            lp = re.search(r"\(if low-profit\)(.*?)(?:\(|$)", desc)
            if lp:
                extra_sufs = _quoted(lp.group(1))
                base_sufs = [s for s in _quoted(desc.split("(if low-profit)")[0])]
                gate = next((k for k in keys if "low_profit" in k), None)
                if gate and base_sufs and extra_sufs:
                    return [a_contains_one_of(key, base_sufs,
                                              extra=(gate, extra_sufs),
                                              anchored=True)]
            return [a_contains_one_of(key, _quoted(desc), anchored=True)]
        return None

    stripped = _strip_parens(desc)

    # ---- mutually exclusive booleans ----
    m = re.match(rf"^({_KEY}) and ({_KEY}) cannot both be true\.?$", stripped)
    if m:
        return [a_mutex_bool(m.group(1), m.group(2))]

    # ---- conditional sentences ----
    if re.match(r"^[Ii]f\b", stripped):
        # conditional suffix requirement keeps quoting from the raw desc
        m = re.match(rf"^If ({_KEY}) is populated and not '([^']+)', it must "
                     rf"contain one of (.+)$", desc)
        if m:
            quoted = _quoted(m.group(3))
            if quoted:
                return [a_contains_one_of(m.group(1), quoted,
                                          skip_values=[m.group(2)],
                                          anchored=True)]
        out = _compile_conditional(desc, schema_enums, keys)
        if out:
            return out
        out = _compile_conditional(stripped, schema_enums, keys)
        if out:
            return out
        return None

    # ---- "Exactly one <key> option / enum value is selected" ----
    m = re.match(rf"^Exactly one ({_KEY}) (?:option|enum value|value)s? is "
                 rf"selected", stripped)
    if m:
        target = m.group(1)
        # only an authoritative enum (schema/mapping) gates the value;
        # prose-quoted tokens are shorthand and can disagree with the data
        return [a_one_of(target, _enum_for(target, schema_enums),
                         required=True)]

    # ---- exactly-one / at-most-one selections (single enum key) ----
    if re.search(r"^(?:Exactly|At most) one of\b", stripped) or \
            re.search(r"is (?:set to )?exactly one of\b", stripped):
        target = None
        m = re.search(rf"\(?({_KEY})\s*(?:∈|in)\s*\{{([^}}]+)\}}", desc)
        allowed = set()
        if m:
            target = m.group(1)
            allowed = set(_quoted("'" + m.group(2).replace("'", "'") + "'")
                          or _quoted(m.group(2)))
            if not allowed:
                allowed = {t.strip().strip("'‘’")
                           for t in m.group(2).split(",") if t.strip()}
        if target is None:
            m = re.match(rf"^({_KEY}) is (?:set to )?exactly one of (.+)$",
                         stripped)
            if m:
                target = m.group(1)
                rest = m.group(2)
                allowed = set(_quoted(rest)) or \
                    {t.strip().strip(".'")
                     for t in rest.split("|") if t.strip()}
        if target is None and len(keys) == 1:
            target = keys[0]
            # the schema/mapping enum is authoritative; prose quotes are
            # shorthand and can disagree with the data model
            allowed = _enum_for(target, schema_enums)
        if target is None:
            return None
        if not allowed:
            allowed = _enum_for(target, schema_enums)
        required = bool(re.search(r"^Exactly one|is (?:set to )?exactly one",
                                  stripped)) and \
            not re.search(r"[Aa]t most one|[Zz]ero is also valid", desc)
        return [a_one_of(target, allowed, required=required)]

    # ---- signer blocks / either-or groups ----
    m = re.match(
        rf"^Exactly one signer block is populated: either ({_KEY})\s*"
        rf"OR \(?({_KEY}) AND ({_KEY})\)?", stripped)
    if m:
        return [a_group_choice([[m.group(1)], [m.group(2), m.group(3)]],
                               exactly_one=True)]
    m = re.match(
        rf"^At least one signer present: ({_KEY}) OR "
        rf"\(?({_KEY}) \+ ({_KEY})\)?", stripped)
    if m:
        return [a_group_choice([[m.group(1)], [m.group(2), m.group(3)]],
                               exactly_one=False)]
    m = re.match(
        rf"^Either \(?({_KEY})\)? is non-empty[^,.]*,? ?(?:or|OR) "
        rf"\(?({_KEY}) (?:AND|and) ({_KEY})\)?[^.]*are both non-empty",
        stripped)
    if m:
        return [a_group_choice([[m.group(1)], [m.group(2), m.group(3)]],
                               exactly_one=False)]

    # ---- at least one of ... is non-empty ----
    if re.match(r"^At least one of\b.*\bis non-empty", stripped) and keys:
        return [a_at_least_one(keys)]

    # ---- "All <N> required-role slots are populated: k1, k2, ..." ----
    m = re.match(r"^All .*? are populated: (.+)$", stripped)
    if m:
        listed = _KEY_RE.findall(m.group(1))
        if listed:
            return [a_nonempty(listed)]

    # ---- officer/director name+address pairing ----
    if re.match(r"^Every populated \S+ has a corresponding", stripped):
        names = [k for k in keys if k.endswith(".name")]
        pairs = [(n, n[: -len(".name")] + ".address") for n in names
                 if n[: -len(".name")] + ".address" in keys]
        if pairs and len(pairs) == len(names):
            return [a_name_address_pairs(pairs)]
        return None

    # ---- both-or-neither blocks ----
    m = re.match(rf"^.*either both ({_KEY}) [Aa][Nn][Dd] ({_KEY}) are set, "
                 rf"or both are empty", stripped)
    if m:
        return [a_both_or_neither(m.group(1), m.group(2))]
    m = re.match(rf"^({_KEY}) and ({_KEY}) are either both populated"
                 rf".*or both empty", stripped)
    if m:
        return [a_both_or_neither(m.group(1), m.group(2))]

    # ---- declarative clause chains: "K is non-empty and ... and ..." ----
    return _compile_declarative(stripped, desc, keys)


def _compile_declarative(stripped, raw_desc, keys):
    """Compile "X [, Y and Z] is/are <predicate> [and <predicate>...]"."""
    # multi-key non-empty: "a, b, and c are (all) non-empty"
    m = re.match(
        rf"^(?:Both )?((?:{_KEY})(?:,? (?:and )?{_KEY})*) are (?:all |both )?"
        rf"non-empty\.?$", stripped)
    if m:
        return [a_nonempty(_KEY_RE.findall(m.group(1)))]

    m = re.match(rf"^(?:Both )?({_KEY}) and ({_KEY}) are not '[^']+'",
                 stripped)
    if m and re.search(r"'Maine'|'ME'", stripped):
        return [a_not_in(m.group(1), _MAINE), a_not_in(m.group(2), _MAINE)]

    m = re.match(rf"^({_KEY})(?:\s*\([^)]*\))?\s+(is|must be|must not be|"
                 rf"does not|matches|equals|differs|is not|should|parses)"
                 rf"\b(.*)$", stripped)
    if not m:
        return None
    key = m.group(1)
    rest = (m.group(2) + m.group(3)).strip()

    assertions = []
    # split the predicate chain conservatively
    clauses = re.split(r"\s+and\s+(?=is\b|not\b|on\b|matches\b|equals\b|"
                       r"contains\b|does\b|from\b|parses\b|should\b|a\b)"
                       r"|;\s*", rest)
    for clause in clauses:
        clause = clause.strip().rstrip(".").strip()
        if not clause:
            continue
        assertion = _match_clause(key, clause)
        if assertion is None:
            # retry without trailing commentary: parentheticals first, then
            # an em-dash tail ("... — cannot terminate before formation")
            bare = re.sub(r"\([^()]*\)", "", clause)
            bare = re.sub(r"\s+", " ", bare).strip().rstrip(".").strip()
            assertion = _match_clause(key, bare)
            if assertion is None and "—" in bare:
                assertion = _match_clause(
                    key, bare.split("—")[0].strip().rstrip(".").strip())
        if assertion is None:
            return None  # unrecognized clause — the whole check stays manual
        assertions.append(assertion)
    return assertions or None


def _match_clause(key, clause):
    """Match one declarative predicate clause for ``key``; None if unknown."""
    if not clause:
        return None
    if re.match(r"^(?:is |must be )?non-?empty$", clause):
        return a_nonempty([key])
    if re.match(r"^is true$", clause):
        return a_truthy([key])
    if re.match(r"^(?:is )?not in the future(?: relative to (?:the "
                rf"submission date|today|{_KEY}))?$", clause):
        mref = re.search(rf"relative to ({_KEY})", clause)
        return a_not_future(key, mref.group(1) if mref else None)
    if re.match(r"^(?:is )?on or before today$", clause):
        return a_not_future(key)
    mm = re.match(rf"^(?:is )?on or before ({_KEY})$", clause)
    if mm:
        return a_date_order(key, "<=", mm.group(1))
    mm = re.match(rf"^(?:is )?on or after ({_KEY})$", clause)
    if mm:
        return a_date_order(key, ">=", mm.group(1))
    mm = re.match(rf"^(?:is )?strictly before ({_KEY})$", clause)
    if mm:
        return a_date_order(key, "<", mm.group(1))
    mm = re.match(rf"^parses as a valid date in the past relative to "
                  rf"({_KEY})$", clause)
    if mm:
        return a_date_order(key, "<=", mm.group(1))
    mm = re.match(rf"^(?:should )?(?:match(?:es)?|equal(?:s)?|"
                  rf"is equal to) ({_KEY})"
                  rf"(?: \(or ({_KEY}) when populated\))?$", clause)
    if mm:
        return a_equals(key, mm.group(1), mm.group(2))
    mm = re.match(rf"^(?:differs from|does not equal|is different from) "
                  rf"(?:both )?({_KEY})(?: and(?: from)? ({_KEY}))?$",
                  clause)
    if mm:
        targets = [mm.group(1)] + ([mm.group(2)] if mm.group(2) else [])
        return a_differs(key, targets)
    if re.match(r"^(?:is |must )?not (?:be )?a P\.?O\.? Box$", clause,
                re.I) or \
            re.match(r"^(?:must not|does not) begin with 'P\.?O\.?'",
                     clause, re.I):
        return a_not_pobox(key)
    if re.match(r"^(?:is )?(?:NOT|not) 'Maine'(?: or 'ME'|\s*/\s*'ME')?$",
                clause):
        return a_not_in(key, _MAINE)
    if re.match(r"^contains a comma$", clause):
        return a_format(key, "contains_comma")
    if re.match(r"^(?:is )?a positive integer$", clause):
        return a_format(key, "positive_integer")
    mm = re.match(r"^should be set to one of \{(.+?)\}", clause)
    if mm:
        vals = set(_quoted(mm.group(1))) or \
            {t.strip().strip("'") for t in mm.group(1).split(",")}
        return a_one_of(key, vals, required=False)
    return None


# --------------------------------------------------------------------------
# loading & evaluation

def load_rubric(form_id, forms_root="forms"):
    path = Path(forms_root) / form_id / "rubric.yaml"
    if not path.exists():
        return {"checks": []}
    import yaml
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {"checks": []}


def _schema_enums(form_id, forms_root):
    """Map dotted canonical keys -> enum value sets.

    Sources: ``schema.json`` enums, overlaid by ``mapping.json`` option keys
    (the mapping is the verified artifact, so its options win).
    """
    out = {}
    path = Path(forms_root) / form_id / "schema.json"
    if path.exists():
        try:
            schema = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            schema = {}

        def walk(node, prefix):
            for k, v in (node.get("properties") or {}).items():
                if not isinstance(v, dict):
                    continue
                dotted = f"{prefix}.{k}" if prefix else k
                if v.get("enum"):
                    out[dotted] = set(str(x) for x in v["enum"])
                walk(v, dotted)
                items = v.get("items")
                if isinstance(items, dict):
                    walk(items, dotted + "[0]")
        walk(schema, "")
    mpath = Path(forms_root) / form_id / "mapping.json"
    if mpath.exists():
        try:
            mapping = json.loads(mpath.read_text(encoding="utf-8"))
            fields = mapping_entries(mapping)
        except Exception:
            fields = {}
        for key, spec in fields.items():
            if not isinstance(spec, dict):
                continue
            if spec.get("field_type") in ("radio", "enum_select",
                                          "enum_text_select"):
                opts = spec.get("options")
                if isinstance(opts, dict) and opts:
                    out[spec.get("canonical_key", key)] = set(opts)
    return out


def evaluate(form_id, case, forms_root="forms", today=None):
    """Evaluate ``form_id``'s rubric checks against ``case``.

    Returns ``{"ok", "form_id", "issues", "stats"}``. ``issues`` is a list of
    ``{code, severity, rubric_severity, check_id, keys, message,
    rule_source}``; ``MANUAL_REVIEW`` entries carry the original prose for
    checks that need human judgment. ``ok`` is False only when an
    error-severity issue is present.
    """
    rubric = load_rubric(form_id, forms_root)
    checks = rubric.get("checks") or []
    enums = _schema_enums(form_id, forms_root)
    ctx = {"today": today or date.today()}
    rule_src = f"forms/{form_id}/rubric.yaml"

    issues = []
    n_machine = n_manual = 0
    for check in checks:
        cid = check.get("id") or "unnamed-check"
        rub_sev = (check.get("severity") or "required").lower()
        sev = _SEV_MAP.get(rub_sev, "error")
        assertions = compile_check(check, enums)
        if assertions is None:
            n_manual += 1
            issues.append({
                "code": "MANUAL_REVIEW",
                "severity": "manual",
                "rubric_severity": rub_sev,
                "check_id": cid,
                "keys": list(check.get("depends_on_keys") or []),
                "message": (check.get("description") or "").strip(),
                "rule_source": f"{rule_src}#{cid}",
            })
            continue
        n_machine += 1
        for assertion in assertions:
            for viol in assertion(case, ctx):
                v_sev = "warning" if viol["code"] == "UNPARSEABLE_DATE" \
                    else sev
                issues.append({
                    "code": viol["code"],
                    "severity": v_sev,
                    "rubric_severity": rub_sev,
                    "check_id": cid,
                    "keys": viol["keys"],
                    "message": viol["detail"],
                    "rule_source": f"{rule_src}#{cid}",
                })

    return {
        "ok": not any(i["severity"] == "error" for i in issues),
        "form_id": form_id,
        "issues": issues,
        "stats": {
            "checks": len(checks),
            "machine_evaluated": n_machine,
            "manual_review": n_manual,
        },
    }


def coverage(forms_root="forms"):
    """Compile-rate report across every form's rubric (no case needed)."""
    root = Path(forms_root)
    total = machine = 0
    per_form = {}
    unmatched = []
    for d in sorted(p for p in root.iterdir() if p.is_dir()):
        path = d / "rubric.yaml"
        if not path.exists():
            continue
        rubric = load_rubric(d.name, forms_root)
        enums = _schema_enums(d.name, forms_root)
        m = t = 0
        for check in rubric.get("checks") or []:
            t += 1
            if compile_check(check, enums) is not None:
                m += 1
            else:
                unmatched.append((d.name, check.get("id"),
                                  (check.get("description") or "").strip()))
        total += t
        machine += m
        per_form[d.name] = (m, t)
    return {"total_checks": total, "machine_evaluated": machine,
            "manual_review": total - machine, "per_form": per_form,
            "unmatched": unmatched}


def _cli(argv):
    if "--coverage" in argv:
        forms_root = next((a for a in argv[1:] if not a.startswith("--")),
                          "forms")
        cov = coverage(forms_root)
        pct = 100.0 * cov["machine_evaluated"] / max(cov["total_checks"], 1)
        print(f"{cov['machine_evaluated']}/{cov['total_checks']} checks "
              f"machine-evaluated ({pct:.1f}%); "
              f"{cov['manual_review']} manual-review")
        if "--unmatched" in argv:
            for fid, cid, desc in cov["unmatched"]:
                print(f"  {fid}#{cid}: {desc[:120]}")
        return 0
    if len(argv) < 3:
        print("usage: python -m engine.rubric <FORM_ID> <case.json> "
              "[forms_root] | --coverage [forms_root] [--unmatched]")
        return 1
    form_id = argv[1]
    case = json.loads(Path(argv[2]).read_text(encoding="utf-8"))
    forms_root = argv[3] if len(argv) > 3 else "forms"
    result = evaluate(form_id, case, forms_root)
    print(json.dumps(result, indent=2))
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    sys.exit(_cli(sys.argv))
