"""catalog/fees.json integrity: shape, coverage, and the no-fabrication rule.

The committed file is regenerated by ``tools/extract_fees.py`` from the
SHA-verified blank PDFs. These checks are PDF-free (CI has no blanks); the
idempotency check runs only when every verified blank is on disk.
"""
import hashlib
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


def _fees():
    return json.loads((ROOT / "catalog" / "fees.json").read_text())


def _known_form_ids():
    index = json.loads((ROOT / "catalog" / "forms_index.json").read_text())
    return {f["form_id"] for f in index["forms"]}


def test_covers_every_form_exactly():
    assert set(_fees()["fees"]) == _known_form_ids()


def test_entry_shape_and_honesty():
    for form_id, e in _fees()["fees"].items():
        assert set(e) >= {"amount", "currency", "source", "note",
                          "printed_lines", "revision"}, form_id
        if e["amount"] is not None:
            # An amount is only ever stored when literally printed.
            assert isinstance(e["amount"], (int, float)), form_id
            assert e["currency"] == "USD", form_id
            assert e["source"] == "printed on form", form_id
            assert e["printed_lines"], (
                f"{form_id}: an amount with no printed evidence")
        else:
            assert e["currency"] is None and e["source"] is None, form_id
            assert e["note"], f"{form_id}: null fee needs a note"
            assert "fee schedule" in e["note"], form_id


def test_no_fee_forms_are_zero():
    fees = _fees()["fees"]
    for form_id in ("CORP_HO-E911", "CORP_RO-E911", "NP_MNPCA-16"):
        assert fees[form_id]["amount"] == 0.0, form_id


def test_meta_coverage_adds_up():
    doc = _fees()
    cov = doc["_meta"]["coverage"]
    assert sum(cov.values()) == len(doc["fees"]) == len(_known_form_ids())


def test_extraction_is_idempotent_when_blanks_present():
    manifest = json.loads(
        (ROOT / "catalog" / "pdf_manifest.json").read_text())["forms"]
    for fid, p in manifest.items():
        pdf = ROOT / "forms" / fid / p["filename"]
        if not pdf.exists():
            pytest.skip("blank PDFs not fetched (CI is PDF-free)")
        if hashlib.sha256(pdf.read_bytes()).hexdigest() != p["sha256"]:
            pytest.skip(f"{fid} blank drifted from the manifest")
    try:
        import fitz  # noqa: F401  (PyMuPDF)
        import pypdf  # noqa: F401
    except ImportError:
        pytest.skip("the committed catalog needs pypdf + pymupdf")

    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    import extract_fees

    committed = _fees()["fees"]
    for form_id in ("CORP_MBCA-6", "CORP_MBCA-12A", "NP_MNPCA-16",
                    "MARK_mark1", "CORP_MBCA-6-1"):
        pdf = ROOT / "forms" / form_id / f"{form_id}.pdf"
        assert extract_fees.extract_one(
            extract_fees._pdf_texts(pdf)) == committed[form_id], form_id
