"""Regenerate docs/STATUS.md from the public form data — no private inputs.

Summarizes every form's field count, confidence mix, and validator review items
(see tools/validate_form.py). Runs offline; commit the result.

    python3 tools/gen_status.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools import validate_form  # noqa: E402

CATEGORIES = {
    "fields.csv": "widget-inventory lag",
    "schema.json": "key not in schema",
    "low confidence": "low confidence",
    "no mapped fields": "no fillable fields",
    "when grammar": "unsupported when",
}


def _category(review):
    for needle, label in CATEGORIES.items():
        if needle in review:
            return label
    return "other"


def main():
    forms = sorted(d.name for d in (ROOT / "forms").iterdir() if d.is_dir())
    manifest = json.loads(
        (ROOT / "catalog" / "pdf_manifest.json").read_text())["forms"]
    index = {f["form_id"]: f for f in json.loads(
        (ROOT / "catalog" / "forms_index.json").read_text())["forms"]}

    rows, tot = [], {"fields": 0, "high": 0, "medium": 0, "low": 0,
                     "errors": 0, "reviews": 0, "review_forms": 0}
    cat_counts = {}
    for fid in forms:
        r = validate_form.validate_form(fid)
        st = r["stats"]
        for k in ("fields", "high", "medium", "low"):
            tot[k] += st.get(k, 0)
        tot["errors"] += len(r["errors"])
        tot["reviews"] += len(r["reviews"])
        if r["reviews"]:
            tot["review_forms"] += 1
        for rev in r["reviews"]:
            cat_counts[_category(rev)] = cat_counts.get(_category(rev), 0) + 1
        rows.append((fid, index.get(fid, {}).get("entity_type", "?"),
                     st["fields"], st["high"], st["medium"], st["low"],
                     len(r["reviews"])))

    fillable = sum(1 for r in rows if r[2] > 0)
    out = []
    out.append("# STATUS\n")
    out.append("Coverage and validation report. Generated by "
               "`tools/gen_status.py` from the public form data.\n")
    out.append("## Summary\n")
    out.append("| Metric | Value |")
    out.append("|--------|-------|")
    out.append(f"| Forms | {len(forms)} |")
    out.append(f"| Fillable forms (>=1 mapped field) | {fillable} |")
    out.append(f"| Total mapped fields | {tot['fields']} |")
    out.append(f"| High confidence | {tot['high']} |")
    out.append(f"| Medium confidence | {tot['medium']} |")
    out.append(f"| Low confidence | {tot['low']} |")
    out.append(f"| Structural errors | {tot['errors']} |")
    out.append(f"| Forms with review items | {tot['review_forms']} |")
    out.append("")
    out.append("### Review items by category\n")
    out.append("| Category | Count |")
    out.append("|----------|-------|")
    for cat, n in sorted(cat_counts.items(), key=lambda kv: -kv[1]):
        out.append(f"| {cat} | {n} |")
    out.append("")
    out.append("Structural errors fail CI. Review items are the per-form "
               "worklist (`python3 tools/validate_form.py <ID> -v`); they do "
               "not fail the build.\n")
    out.append("## Per-form coverage\n")
    out.append("| Form | Entity | Fields | High | Med | Low | Reviews |")
    out.append("|------|--------|-------|------|-----|-----|---------|")
    for fid, ent, n, hi, md, lo, rv in rows:
        out.append(f"| {fid} | {ent} | {n} | {hi} | {md} | {lo} | {rv} |")
    out.append("")

    (ROOT / "docs" / "STATUS.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote docs/STATUS.md: {len(forms)} forms, {tot['fields']} fields, "
          f"{tot['errors']} errors, {tot['reviews']} reviews")


if __name__ == "__main__":
    main()
